title: '<dd>: The Description Details element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/dd
tags:
    group: Text content
api: HTMLElement
permitted-aria-roles: none
tag_omission:
browser-compatibility: html.elements.dd
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
