title: '<caption>: The Table Caption element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/caption
tags:
    group: Table content
api: HTMLTableCaptionElement
permitted-aria-roles: none
tag_omission:
browser-compatibility: html.elements.caption
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
