examples:

    - name: simple-video-example
      title: Simple video example
      size:
          width: 640
          height: 370

    - name: multiple-sources-example
      title: Multiple sources example
      size:
          width: 640
          height: 370
