recipe:
    name: html-element
    references:
        interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html
        specifications:
            - link: https://html.spec.whatwg.org/multipage/embedded-content.html#the-video-element
              status: Living Standard
        browser-compatibility: html.elements.video
        examples:
            - title: Simple video example
              html-source: live-examples/simple-video-example/example.html
              description: live-examples/simple-video-example/description.md
              size:
                  width: 640
                  height: 370
            - title: Multiple sources example
              html-source: live-examples/multiple-sources-example/example.html
              description: live-examples/multiple-sources-example/description.md
              size:
                  width: 640
                  height: 370
        attributes:
            element-specific: ./attributes
            global-attributes: /html/global_attributes