interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html
specifications:
    - link: https://html.spec.whatwg.org/multipage/embedded-content.html#the-video-element
      status: Living Standard
browser-compatibility: html.elements.video